source 'https://github.com/CocoaPods/Specs.git'

target 'PIVideoPlayer', :exclusive => true do
  pod "PIVideoPlayer", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PIVideoPlayer", :path => "../"

  
end
